server:
  port: 8080

spring:
  application:
    name: toolkit-web
  servlet:
    multipart:
      max-file-size: 100MB # 设置单个文件的最大长度
      max-request-size: 300MB # 设置最大的请求文件的大小
      file-size-threshold: 1MB  # 当上传文件达到1MB的时候进行磁盘写入
      location: /tmp  # 上传的临时目录
